### ISSUE TITLE
Advantage 360 Pro ( BLE ) on FreeBSD 13.2-RELEASE-p2 GENERIC amd64

### ISSUE THREAD

**Issue by Dmitry-N-Medvedev** [takawata/FreeBSD-BLE#14]
good morning, nice community :)

**the context**:
1. DEVICE: an Advantage 360 Pro keyboard; works over BLE
2. OS: FreeBSD 13.2-RELEASE-p2 GENERIC amd64
3. Bluetooth USB dongle (  <Broadcom BCM2070B0, class 9/0, rev 2.00/1.00, addr 3> on usbus0 )
4. all the services in regards to bluetooth are installed/running

**the problem**: cannot pair the said keyboard. Help needed :)

**the workflow**

$ doas service hcsecd restart
Stopping hcsecd.
Waiting for PIDS: 18080.
Starting hcsecd.

$ doas service sdpd restart
Stopping sdpd.
Waiting for PIDS: 18149.
Starting sdpd.

$ doas service bthidd restart
Stopping bthidd.
Waiting for PIDS: 18218.
Starting bthidd.

$ doas service devd restart
Stopping devd.
Waiting for PIDS: 18278.
Starting devd.

$ doas service bluetooth restart ubt0
ng_l2cap_lower_rcvmsg: ubt0l2cap - HCI node is up, bdaddr: 84:a4:66:7b:a8:d6, pkt_size=1021 bytes, num_pkts=8

$ doas hccontrol le_enable enable
LE enabled

$ doas hccontrol le_set_scan_enable enable
LE Scan: Enabled

<now, turn the keyboard to pairing mode>

dmitry@z420 ~ $ doas hccontrol read_neighbor_cache
T BD_ADDR           Features                Clock offset Page scan Rep. scan
R **4d:7a:60:12:c6:7e** 00 00 00 00 00 00 00 00            0      0xc3         0
	Complete local name: **Adv360 Pro**
	Appearance: c1 03
	Flags: 06
	Incomplete list of service class UUIDs (16-bit): 12 18 0f 18

P 40:22:d8:c3:bc:c2 00 00 00 00 00 00 00 00            0      0xb4         0
	Flags: 06
	Manufacturer: Etekcity Corporation
	Manufacturer specific data: 01 c2 bc c3 d8 22 40 05 07 02 02 02

R e3:ac:28:e0:43:bb 00 00 00 00 00 00 00 00            0      0xc1         0
	Flags: 04
	Manufacturer: Anhui Huami Information Technology Co., Ltd.
	Manufacturer specific data: 02 ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff 03 e3 ac 28 e0 43 bb

P 50:8a:06:f4:af:94 00 00 00 00 00 00 00 00            0      0xb2         0
	Flags: 06
	Incomplete list of service class UUIDs (16-bit): 01 a2
	Service data: 01 a2 01 4f 91 e0 d7 65 7f 77 1d 46 1f 77 c8 46 7e a2 8a

$ doas hccontrol le_set_scan_enable disable
LE Scan: Disabled

$ doas lehid -r 4d:7a:60:12:c6:7e
CONNECT
CONNECTOK
no more rows available
OP 4: Handle 002b CODE a
UPDATE ble_service SET high_attribute_id=(SELECT max(attribute_id) from ble_attribute) WHERE (service_id = (SELECT max(service_id) FROM ble_service) AND device_id = (SELECT max(device_id) FROM ble_device));
0 1
01 18
0 9
00 18
0 18
0a 18
0 25
12 18
0x10e615691af0 0x10e61568a780
33 86
0 2
20 03 00 05 2a
34 89
0 5
0a 06 00 29 2b
35 91
0 7
02 08 00 2a 2b
36 94
0 10
02 0b 00 00 2a
37 96
0 12
02 0d 00 01 2a
38 98
0 14
02 0f 00 a6 2a
39 100
0 16
02 11 00 04 2a
40 103
0 19
02 14 00 24 2a
41 105
0 21
02 16 00 29 2a
42 107
0 23
02 18 00 50 2a
43 110
0 26
02 1b 00 4a 2a
44 112
0 28
02 1d 00 4b 2a
45 114
0 30
12 1f 00 4d 2a
46 118
0 34
0c 23 00 4d 2a
47 121
0 37
12 26 00 4d 2a
48 125
0 41
04 2a 00 4c 2a
PROBE_INCLUDE
0x10e61568f570 0x10e61568a780
ID9: 00001801-0000-1000-8000-00805f9b34fb
21 00002a05-0000-1000-8000-00805f9b34fb
22 00002b29-0000-1000-8000-00805f9b34fb
23 00002b2a-0000-1000-8000-00805f9b34fb
GAP:10
0 11
41 64 76 33 36 30 20 50 72 6f
Device Name  Adv360 Pro
0 13
c1 03
Apperance  961
0 17
0c 00 18 00 1e 00 58 02
Connection Parameters 12 24 30
DIS:11
0 20
41 64 76 33 36 30 20 50 72 6f
Model No Adv360 Pro
0 22
4b 69 6e 65 73 69 73 20 43 6f 72 70 6f 72 61 74 69 6f 6e
Manifacture Name Kinesis Corporation
0 24
01 50 1d 5e 61 01 00
PnPID 01 1d50 615e 0001
HOGP:12
STMT10x10e61568af00
0 27
00 00 00 03
HID Version:0 Country Code 0 FLAG:3
6
0 29
OP a: Handle 001d CODE f
Cannot read REPORT MAP -1

**what should I do next?**
I am lost, will appreciate any help

:)

best regards,
Dmitry

**Comment by takawata** [comment]
Try 
% sudo ./lepair -r 4d:7a:60:12:c6:7e
then you will getotput something like 
 ```
device{
        name "thisdevice";
        bdaddr 4d:7a:60:12:c6:7e ;
        addrtype lerand;
        ediv 0x????;
        rand 0x??????????????;
        key 0x????????????????????????;
        pin nopin;
 `}`
```
then paste this entry into hcsecd.conf in lesecd directory and run 
%  sudo ./lesecd 
After that, 
% ./lehid -s -r  4d:7a:60:12:c6:7e
lehid with -s option  wait until secure connection is established by lesecd.

**Comment by Dmitry-N-Medvedev** [comment]
hi @takawata,

1. the doas lehid -r 4d:7a:60:12:c6:7e hangs with the same "Cannot read REPORT MAP -1"
2. the lepair -r 4d:7a:60:12:c6:7e says "Operation now in progress"

maybe I should shutdown some services that might interfere with this?

**Comment by takawata** [comment]
1. HID over GATT requires encrypted connection, per specification.
2. lepair  requires privilages to add short term encryption.
And  lepair supports old pairing scheme which requires larger MTU. So if the device only accepts newer scheme, it cannot be paired.

**Comment by Dmitry-N-Medvedev** [comment]
shut down all the services but the bluetooth and tried lehid and in a new terminal lepair.

the lapair says operation timeout

**Comment by Dmitry-N-Medvedev** [comment]
> 1. HID over GATT requires encrypted connection, per specification.
> 2. lepair  requires privilages to add short term encryption.
>    And  lepair supports old pairing scheme which requires larger MTU. So if the device only accepts newer scheme, it cannot be paired.

okay. then let's call it a day. Closing this.

**Comment by takawata** [comment]
One point, Do you make sure entering pairing mode before  invoke lepair?
