### ISSUE TITLE
BLE and Wireless Connectivity 802.11b/g/n

### ISSUE THREAD

**Issue by sparvu** [takawata/FreeBSD-BLE#2]
Im planning to integrate and test under FreeBSD 12.0 Raspberry PI3B+ two radio components, at the same time:
* a CSR8501 Bluetooth USB dongle
* Wifi 802.11b/g/n USB dongle 

Do you think we can use at the same time, using USB 2.0 ports such setup without any interference or conflicts ? Im asking because BLE uses same 2.4GHz as the wireless network connectivity. 

Any ideas ?

**Comment by takawata** [comment]
Probably yes. 
I use BT dongle and built-in iwm(4)  in my PC. 
BT and wifi dual adapter should be more desirable because it may implement bluetooth coexistence protocol.

**Comment by sparvu** [comment]
cool. good point. I could try to find a single dongle with BLE and Wifi within. Lets see if I can find any.

**Comment by sparvu** [comment]
thanks for help and pointers.

**Comment by sparvu** [comment]
Closing this.
