### ISSUE TITLE
porting to FreeBSD

### ISSUE THREAD

**Issue by oldoldman** [takawata/FreeBSD-BLE#7]
Hi @takawata, I want to know if these tools have ported to FreeBSD or not. If ported, what is the keyword to search ? Many thank!!!

**Comment by takawata** [comment]
These tools are for FreeBSD bluetooth stack, and the stack is not used other than FreeBSD.

**Comment by oldoldman** [comment]
Thanks. I've found the le_enable command, though it is not documented in man hccontrol(8).
